### ISSUE TITLE
Install error 71

### ISSUE THREAD

**Issue by Altlock** [cbsd/reggae#11]
When installing Reggae(downloaded with git clone) on FreeBSD 11.1 with `make install`, the following occurs.

https://pastebin.com/b29Yh2p7

**Comment by Altlock** [comment]
Temporary workaround for me was to delete the `MAN_PAGES = ` lines in the Makefile.
I'm currently testing CBSD and Reggae, so if I come by anything lacking or not working, I'll either fix and push or make an issue so you are aware of it. Also, I want to complement you for building the cbsd software @mekanix.

**Comment by mekanix** [comment]
The procedure is "make && make install" as root. That will compress man pages and install won't complain any more. Thank you for the kind words, I really appreciate it, but most of the code was written by @olevole who is the lead developer. Reggae is currently only my toy, but I hope I'll find the time today to record that video.

**Comment by mekanix** [comment]
https://www.youtube.com/watch?v=6GPKO6Gp7b0

**Comment by mekanix** [comment]
https://www.youtube.com/watch?v=sShfqitboJU
