### ISSUE TITLE
It probably does not work if ip4_addr has several IPs

### ISSUE THREAD

**Issue by olevole** [cbsd/reggae#9]
Just comment:

https://github.com/cbsd/reggae/blob/8b64959e0675094661739309524ce92a0f56a8ea/scripts/register.sh#L14

Probably, it will be better here ${ipv4_first} variable ( https://www.bsdstore.ru/en/11.1.x/wf_cbsd_variables_ssi.html ), because the ip4_addr can have the form:

```
ip4_addr="10.0.0.2/24,192.168.0.2,2a01:4f8:171:2985::3/64"
```

This variables always contain only one IP:

> ${ipv4_first_public} | (jail, bhyve) :: first public IPv4 address of the environment
> ${ipv4_first_private} | (jail, bhyve) :: first private IPv4 address of the environment
> ${ipv4_first} | (jail, bhyve) :: first (any) IPv4 address of the environment

**Comment by mekanix** [comment]
Format of ip4_addr sounds like it contains ipv6 address. If yes, how would I use it? If that's possible, it would solve DHCP updating PF on the host, as pfctl requires ipv6 addr configured.

**Comment by olevole** [comment]
yes,  **ip4_addr** ( despite its name ;-) ) may contains IPv6 address. 
Try using **${ipv4_first} ** variable instead. It is more suitable for DDNS because the ip4_addr ( besides Ipv6 ) may contains several IPs (alias), while $ip4_first always return only first IPv4 address

**Comment by olevole** [comment]
besides, if I'm not mistaken, $ipv4_first return IP without prefixes, not necessary for `cut -f -d ` here. But it's better to check )
